server:
  port: 8000
spring:
  application:
    name: zuul
zuul:
  routes:
    clients:
      path: /client/**
      service-id: client
    client2:
      path: /client2/**
      service-id: client2
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/
management:
  endpoints:
     web:
   #   base-path: / #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      exposure:
       include: '*' #开放所有页面节点  默认只开启了health、info两个节点