server:
  port: 8200
spring:
  application:
    name: hystrix-turbine
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
management:
#  server:
#    port: 9007
  endpoints:
    web:
#      base-path: /monitor #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      exposure:
        include: '*'  #开放所有页面节点  默认只开启了health、info两个节点

turbine:
  aggregator:
    cluster-config: default     #需要监控的服务集群名
  app-config: zuul    #需要监控的服务名
  cluster-name-expression: new String("default")
  instanceUrlSuffix: /actuator/hystrix.stream
#      